# Site settings
title: Ajinkya's CV 
description: Ajinkya's CV
favicon: /assets/img/avatar.jpg
baseurl: /
url: https://ajinkyabapat.github.io/
rss_url: /pages/atom.xml
google_analytics: UA-63653234-1

# Build settings
markdown: kramdown

exclude: [vendor]

# Author settings
author:
  name: Ajinkya Bapat
  title: DevOps Engineer
  address: Pune, India
  email: ajinkyabapat12@gmail.com
  link: http://ddbullfrog.com
  weibo:
  github: AjinkyaBapat
  linkedin: ajinkyabapat
  twitter: ajinkyab12
  gavatar: /resumecard/assets/img/avatar.JPG
  stackoverflow: 6202024
#  stackoverflow: 4582127
  workHistory:
    - work1:
      company: Ignite Solutions Pvt. Ltd.
      location: Pune, India
      title: DevOps Engineer
      started: 2017
      duration: (2017 - Present)
      description: 
    - work2:
      company: DXC Technology
      location: Bangalore, India
      title: DevOps Engineer
      started: 2017
      duration: (Apr 2017 - Aug 2017)
      description: 
    - work3:
      company: Hewlett Packard Enterprise
      location: Bangalore, India
      title: DevOps Engineer
      started: 2016
      duration: (Feb 2016 - Mar 2017)
      description: 
  educationHistory:
    - education1:
      organization: University Of Pune
      location: Kopargaon, India
      degree: Bachelor
      major: Computer Engineering
      started: 2012
      duration: (2012 - 2015)
      description: 
    - education2:
      organization: MSBTE
      location: Kopargaon, India
      degree: Diploma
      major: Information Technology
      started: 2009
      duration: (2009 - 2012)
      description: 

  languages:
    - language1:
      name: English
      proficiency: Professional
    - language2:
      name: Hindi
      proficiency: Professional
    - language3:
      name: Marathi
      proficiency: Native
    - language4:
      name: Spanish
      proficiency: Basic
  programmingSkills:
    - skill1:
      name: DevOps Methodologies
      percentage: 70%
    - skill2:
      name: Config. Mgmt.
      percentage: 80%
    - skill3:
      name: CI/CD
      percentage: 70%
    - skill4:
      name: Cloud (AWS|Azure|GCP) 
      percentage: 60%
    - skill5:
      name: Containerization
      percentage: 80%
    - skill6:
      name: PYTHON|JAVA|C|HTML|CSS|Javascript
      percentage: 60%
